import java.awt.Image;
import java.awt.Toolkit;
import java.sql.DriverManager;
import java.sql.*;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shreyas
 */
public class Notifications extends javax.swing.JFrame {

    /**
     * Creates new form Notifications
     */
    public Notifications() {
        initComponents();
       // scaleImage();
    }
    Notifications(String userid)
    {   initComponents();
        //scaleImage();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
            jLabel1.setText(userid);
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            ResultSet rs = null;
            String icode,iname,brand,qnty,threshold,price,difference,category;
            try
            {   
                model.setRowCount(0);
                Class.forName("java.sql.DriverManager");
                java.sql.Connection con=(java.sql.Connection)DriverManager.getConnection
                (EZStockerDataSource.connect,EZStockerDataSource.userid,EZStockerDataSource.passwd);
                java.sql.Statement stmt=(java.sql.Statement)con.createStatement();
                String query1="SELECT itemcode,name,category,brand,quantity,threshold,price,threshold-quantity as difference"
                + " FROM ITEM WHERE userid='"+userid+"' and quantity<threshold;";
                rs = stmt.executeQuery(query1);
                while (rs.next())
                {
                    icode =rs.getString("ItemCode");
                    iname=rs.getString("Name");
                    brand = rs.getString("brand");
                    category = rs.getString("category");
                    qnty = rs.getString("quantity");
                    threshold = rs.getString("threshold");
                    price=rs.getString("price"); 
                    difference=rs.getString("difference");
                    model.addRow(new Object[] {icode,iname,brand,category,qnty,threshold,difference,price});


                }
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog (this, e.getMessage());
            }
             
       
       
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, 130, 39));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel2.setText("Welcome");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 120, 39));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel3.setText("The following Items need your attention");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 700, 60));

        jTable1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Code", "Item name", "Brand", "Category", "Quantity", "Threshold", "Difference", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(23);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 828, 250));

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refresh.jpg"))); // NOI18N
        jButton1.setToolTipText("Refresh");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 250, 40, 30));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 120, 80));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String userid=jLabel1.getText();
    DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        ResultSet rs = null;
        String icode,iname,brand,qnty,threshold,price,difference,category;
        try
        {   
            model.setRowCount(0);
            Class.forName("java.sql.DriverManager");
            java.sql.Connection con=(java.sql.Connection)DriverManager.getConnection
            (EZStockerDataSource.connect,EZStockerDataSource.userid,EZStockerDataSource.passwd);
            java.sql.Statement stmt=(java.sql.Statement)con.createStatement();
            String query1="SELECT itemcode,name,category,brand,quantity,threshold,price,threshold-quantity as difference"
            + " FROM ITEM WHERE userid='"+userid+"' and quantity<threshold;";
            rs = stmt.executeQuery(query1);
            while (rs.next())
            {
                icode =rs.getString("ItemCode");
                iname=rs.getString("Name");
                brand = rs.getString("brand");
                category = rs.getString("category");
                qnty = rs.getString("quantity");
                threshold = rs.getString("threshold");
                price=rs.getString("price"); 
                difference=rs.getString("difference");
                model.addRow(new Object[] {icode,iname,brand,category,qnty,threshold,difference,price});
                

            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog (this, e.getMessage());
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Notifications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Notifications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Notifications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Notifications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Notifications().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
